name: CI

on:
  push:
    branches: [ "test_437109" ]
  pull_request:
    branches: [ "test_437109" ]

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run circle unittests
      run: |
        python -m unittest test_circle.py -f
    - name: Run rectangle unittests
      run: |
        python -m unittest test_rectangle.py -f
    - name: Run square unittests
      run: |
        python -m unittest test_square.py -f
    - name: Run triangle unittests
      run: |
        python -m unittest test_triangle.py -f
  
  test_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run circle unittests
      run: |
        python -m unittest test_circle.py -f
    - name: Run rectangle unittests
      run: |
        python -m unittest test_rectangle.py -f
    - name: Run square unittests
      run: |
        python -m unittest test_square.py -f
    - name: Run triangle unittests
      run: |
        python -m unittest test_triangle.py -f
