name: CI

on:
  push:
    branches: [ "test_437109" ]
  pull_request:
    branches: [ "test_437109" ]

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run circle unittests
      continue-on-error: true
      run: |
        python -m unittest test_circle.py
    - name: Run rectangle unittests
      continue-on-error: true
      run: |
        python -m unittest test_rectangle.py
    - name: Run square unittests
      continue-on-error: true
      run: |
        python -m unittest test_square.py
    - name: Run triangle unittests
      continue-on-error: true
      run: |
        python -m unittest test_triangle.py
  
  test_windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run circle unittests
      continue-on-error: true
      run: |
        python -m unittest test_circle.py
    - name: Run rectangle unittests
      continue-on-error: true
      run: |
        python -m unittest test_rectangle.py
    - name: Run square unittests
      continue-on-error: true
      run: |
        python -m unittest test_square.py
    - name: Run triangle unittests
      continue-on-error: true
      run: |
        python -m unittest test_triangle.py
